sonar.host.url=https://sonarqube.box2home.xyz/
sonar.projectKey=MS-PROJECT:geocaching
sonar.projectName=geocaching-microservice
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/** , **/*.html ,**/*.css ,**/assets/** , **/*.js 



sonar.tests=src/
sonar.language=js
sonar.test.inclusions= **/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/angular/lcov.info
 